application:
  name: stellarcraftcontrol
server:
  port: 8080
  servlet:
    context-path: /stellar-craft

spring:
  datasource:
    url: jdbc:h2:file:/Users/sabrinaberazategui/proyectos1/stellarcraftcontrol/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    open-in-view: false
    show-sql: true
  jmx:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n'
    file: '%d{HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n'
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.hibernate: INFO
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /api-docs




